env:
    CONFIG: change.sh
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: "/tmp/ci"
    CIRRUS_SHELL: bash
    
task:
    name: lavaaosp
    timeout_in: 4h
    container:
      image: aarunalr/aosp-build
      cpu: 8
      memory: 32g
    
    download_ccache_background_script: # To download ccache in background
      - ./download_ccache # Ccache download script
    sync_script: # To sync source
      - ./sync # Source sync script
    monitor_background_script: # To monitor ccache and machine status every minute, runs in background
      - ./monitor # Monitor script
    build_script: # Actual build script foreground
      - ./build # Build script to run
    upload_ccache_script: # Upload ccache to cloud foreground
      - ./upload_ccache # Ccache uploading script
