env:
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: "/tmp/ci"
    
task:
    name: lava-aosp
    timeout_in: 4h
    container:
      image: aarunalr/aosp-build
      cpu: 8
      memory: 32g
    
    setup_script:
      - bash setup.sh
    dccache_script:
      - bash dccache.sh
    sync_script:
      - bash sync.sh
    build_script:
      - bash build.sh
    upload_script:
      - bash uccache.sh
