env:
    CONFIG: change.sh
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: "/tmp/ci"
    CIRRUS_SHELL: bash

task:
    name: lavaaosp
    timeout_in: 4h
    container:
      image: aarunalr/aosp-build
      cpu: 8
      memory: 32g
    
    setup_script:
      - bash setup.sh
    change_script:
      - bash change.sh
    sync_script:
      - bash sync.sh
    lunch_script:
      - bash lunch.sh      
    build_script:
      - bash build.sh
