#!/bin/bash
cd /tmp/rom

ROM_LINK=https://github.com/ProjectBlaze/manifest
ROM_BRANCH=12.1
DEVICE_BRANCH=blaze
DEVICE_LUNCH=blaze_lava-userdebug

# git configs
git config --global user.email "orkun68100@gmail.com"
git config --global user.name "Orkun Ergun"
git config --global color.ui true

# sync rom
repo init --depth=1 --no-repo-verify -u ${ROM_LINK} -b ${ROM_BRANCH} -g default,-mips,-darwin,-notdefault
git clone https://gitlab.com/68orkun/local_manifest.git --depth 1 -b ${DEVICE_BRANCH} .repo/local_manifests
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8

source build/envsetup.sh
lunch ${DEVICE_LUNCH}
brunch lava

curl -T *.zip https://oshi.at/ccache.zip/129600
