#!/bin/bash
cd /tmp/rom

ROM_LINK=https://github.com/ProjectBlaze/manifest
ROM_BRANCH=12.1
DEVICE_BRANCH=blaze
DEVICE_LUNCH=blaze_lava-userdebug

# git configs
git config --global user.email "orkun68100@gmail.com"
git config --global user.name "Orkun Ergun"
git config --global color.ui true

source build/envsetup.sh
lunch ${DEVICE_LUNCH}
brunch lava

curl -T *.zip https://oshi.at/ccache.zip/129600
