#!/bin/bash
cd /tmp/rom

ROM_LINK=https://github.com/PixelOS-Pixelish/manifest
ROM_BRANCH=twelve
DEVICE_BRANCH=pos
DEVICE_LUNCH=aosp_lava-userdebug

# git configs
git config --global user.email "orkun68100@gmail.com"
git config --global user.name "Orkun Ergun"
git config --global color.ui true

# sync rom
repo init --depth=1 --no-repo-verify -u ${ROM_LINK} -b ${ROM_BRANCH} -g default,-mips,-darwin,-notdefault
git clone https://github.com/r9lab/local_manifest.git --depth 1 -b ${DEVICE_BRANCH} .repo/local_manifests
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8

source build/envsetup.sh
lunch ${DEVICE_LUNCH}
mka bacon

curl -T *.zip https://oshi.at/ccache.zip/129600
